[package]
name = "double_range_slider"
version = "0.1.0"
authors = ["Hacknus <l_stoeckli@bluewin.ch>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"
publish = false


[dependencies]
eframe = { path = "../../crates/eframe" }
tracing-subscriber = "0.3"
